# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField()),
            ],
        ),
    ]
