# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.users'),
        ),
    ]
