# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160713_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user_id',
        ),
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('1', '\u666e\u901a\u7528\u6237'), ('2', '\u7ba1\u7406\u5458'), ('3', '\u8d85\u7ea7\u7ba1\u7406\u5458')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='score',
        ),
    ]
