# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 01:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160713_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='time',
            new_name='c_time',
        ),
        migrations.AddField(
            model_name='users',
            name='u_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 14, 1, 22, 0, 17000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
